name: BrowserStack Web Tests

on:
  workflow_call:
    inputs:
      SERVICE_LOCATION:
        required: true
        type: string
      BUILD_ARTIFACT:
        required: true
        type: string
    secrets:
      BROWSERSTACK_USERNAME:
        required: true
      BROWSERSTACK_ACCESS_KEY:
        required: true          

jobs:
    web-test:
      runs-on: ubuntu-latest
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'   
    
      - name: Run tests
        run: |
           cd ${{ inputs.SERVICE_LOCATION }}
           mvn clean test -DtestngXmlFile="TestNg.xml"
        
      - name: Save test reports
        uses: actions/Upload-artifact@4v3
        if: success() || failure()
        with:
          name: test-reports
          path: ${{ inputs.SERVICE_LOCATION }}/${{ inputs.BUILD_ARTIFACT }}
        
